export const deskMatgenericKeywords = [
  'extended mouse pad',
  'mouse pad',
  'new job gift',
  'tech accessories',
  'gaming mouse mat',
  'large mouse pad',
  'desk pad',
  'gaming mouse pad',
  'mouse mat',
  'desk mat',
  'desk accessories',
  'work from home gifts',
  'mouse pad',
  'keyboard mat',
  'desk mat',
  'xxl mouse pad',
];

export const pillowGenericKeywords = [
  'bench cushion',
  'bench cushion indoor',
  'chair cushion',
  'cushion',
  'cushion for bench',
  'floor cushion',
  'decorative pillow',
  'decorative pillows',
  'interior design',
  'seat cushion',
  'bench seat cushion',
  'plush',
  'throw pillow for bed',
];

export const blanketGenericKeywords = [
  'boho throw blanket',
  'camping blanket',
  'cozy blanket',
  'dog blanket',
  'fleece blanket',
  'halloween blanket',
  'pet blanket',
  'picnic blanket',
  'soft blanket',
  'throw blanket',
  'tapestry blanket',
  'throw blanket couch',
];

export const wovenBlanketGenericKeywords = [
  'woven blanket',
  'woven throw blanket',
  'woven cotton blanket',
  'boho throw blanket',
  'camping blanket',
  'cozy blanket',
  'dog blanket',
  'fleece blanket',
  'halloween blanket',
  'pet blanket',
  'picnic blanket',
  'soft blanket',
  'throw blanket',
  'tapestry blanket',
  'throw blanket couch',
];
