export const deskMatgenericKeywords = [
  'extended mouse pad',
  'mouse pad',
  'new job gift',
  'tech accessories',
  'gaming mouse mat',
  'large mouse pad',
  'desk pad',
  'gaming mouse pad',
  'mouse mat',
  'desk mat',
  'desk accessories',
  'work from home gifts',
  'mouse pad',
  'keyboard mat',
  'desk mat',
  'xxl mouse pad',
];

export const pillowGenericKeywords = [
  'pillow',
  'cushion',
  'sofa cushion',
  'sofa pillow',
  'bed pillow',
  'bed cushion',
  'chair cushion',
  'chair pillow',
  'home decor',
  'home accessories',
  'house warming gift',
  'housewarming gift',
];
